language: node_js
node_js:
  - '12'
services:
  - docker

before_install:

script:
  - echo "$DOCKER_PASSWORD"
  - echo "$DOCKER_USERNAME"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t dbllm/docker-front:latest .
  - docker push dbllm/docker-front:latest