language: node_js
node_js:
  - '12'
services:
  - docker

before_install:

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t  dbllm/docker-front:main .
  - docker push dbllm/docker-front:main